apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: onboarding-bot-staging
  name: onboarding-bot-model
spec:
  template:
    spec:
      containers:
      - name: onboarding-bot-model
        image: devlaunchers/onboarding-bot-model
        ports:
        - containerPort: 8080
        env:
        - name: HUGGINGFACEHUB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: onboarding-bot-model-secrets
              key: huggingfacehub-api-token
      readinessProbe:
        exec:
          command: "echo hi"
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule