apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onboarding-bot-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/onboarding-bot-model
  newName: devlaunchers/onboarding-bot-model
  newTag: 4f1f23d-202405110024 # {"$imagepolicy": "onboarding-bot-staging:onboarding-bot-model:tag"}
